config/routes.rb
Rails.application.routes.draw do


#devise
  devise_for :users, controllers: { registrations: 'users/registrations' }

#root page
  root 'static_pages#home'

#jobs
  resources :jobs
  get  '/new',  to: 'jobs#new'
  get  '/view', to: 'jobs#view'

# applied user
  resources :applied_users, only: [:destroy, :show] do
  	post ':job_id' => "applied_users#create", on: :collection, as: :new
  end
end

app/models/job.rb
class Job < ApplicationRecord
#database relation
  belongs_to :user
  has_many :applied_users, dependent: :destroy
  has_many :applied_job_users, through: :applied_users, source: "user"

#validations
  validates :post, presence: true
  validates :salary, presence: true, numericality: { only_integer: true }
  validates :experience, presence: true, numericality: { only_integer: true }

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
#before action
before_action :authenticate_user!

#methods
  def index
    @jobs = Job.all.page(params[:page]).per(8)
    if current_user.has_role? :admin
      @jobs = current_user.jobs.page(params[:page]).per(8)
    end
  end

  def view
    if current_user.has_role? :admin
      @jobs = current_user.jobs.page(params[:page]).per(8)
    else
      redirect_to jobs_path
    end
  end

  def new
	  @job = Job.new
  end

  def create
  	@job = current_user.jobs.build(job_params)
    if @job.save
      flash.now[:success] = "Job created!"
      redirect_to jobs_path
    else
      flash.now[:danger] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.user = current_user
    if @job.update_attributes(job_params)
      flash.now[:success] = "Your have successfully updated your job"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
  	 @job = Job.find(params[:id])
  	 if @job.destroy
  	 	flash.now[:success] = "You job has been successfully deleted"
  	 	redirect_to jobs_path
  	 else
  	 	flash.now[:danger] = "Something my not be right"
  	 end
  end


#User- define variables
private

  def job_params
    params.require(:job).permit(:post, :experience, :salary)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_common_form.html.erb
<%= form_for(@job) do |f| %>

    <%= f.label :Post %>
    <%= f.text_field :post, autofocus: true,  class: 'form-control',autocomplete: "post", placeholder:"Post"%>

    <%= f.label :"Experience"  %>
    <%= f.text_field :experience, class: 'form-control', autocomplete: "experience", placeholder:"In Years"%>

    <%= f.label :"salary" %>
    <%= f.text_field :salary, class: 'form-control', autocomplete: "off", placeholder:"Per/Month" %>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>
<%= link_to "Back", :back %>
<br/><br/><br/><br/>
<br/><br/><br/><br/>
<br/><br/>

app/views/jobs/_error_message.html.erb
<% if @job.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <% @job.errors.full_messages.each do |msg| %>
        <span><%= msg %></span><br/>
      <%end%>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<% provide(:title, 'Edit Job') %>
<% provide(:button_text, "Save Changes") %>

<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>

    <div class="col-md-4">
      <h3>Edit <%= @job.post.capitalize %></h3>
        <br/>
        <%= render 'common_form' %>
    </div>

    <div class="col-md-4">
    </div>

  </div>
</div>

app/views/jobs/index.html.erb
<%#= current_user.jobs.inspect %>
<%#= current_user.applied_jobs.inspect %>
<div class="container">
<% if current_user.has_role? :admin %>
  <% provide(:title, 'My jobs') %>
    <h3>My Jobs</h3>
    <hr/>
      <table id="customers" >
      <tr>
          <th>Job Title</th>
          <th>Experience (in Years)</th>
          <th>Salary (per/month)</th>
          <th>Applied User</th>
          <th>Edit Job</th>
          <th>Delete Job</th>
        </tr>
          <% @jobs.each do |job| %>
            <tr>
              <!-- <td><%#= job.applied_job_users.inspect %></td> -->
              <td><%= job.post %></td>
              <td><%= job.experience %></td>
              <td><%= job.salary %></td>
              <td><%= link_to 'Applied User', applied_user_path(job) %></td>
              <td><%= link_to 'Edit', edit_job_path(job) %></td>
              <td><%= link_to 'Destroy',job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
           <% end %>
      </table>
      <hr/>
      <div id="paginate">
        <%= paginate @jobs %>
      <br/><br/><br/><br/><br/>
      <br/><br/><br/><br/><br/>
      <br/><br/><br/><br/><br/>
      <br/>
      </div>
<% else %>
  <% provide(:title, 'All jobs') %>
    <h3> All Jobs </h3>
    <hr/>
    <table id="customers" >
      <tr>
          <th>Job Title</th>
          <th>Experience (in Years)</th>
          <th>Salary (per/month)</th>
          <th>Apply/Cancel</th>
        </tr>
          <%# user_applied_jobs = current_user.applied_jobs %>
          <% @jobs.each do |job| %>
            <%#= job.applied_users.inspect %>
            <tr>
              <td><%= job.post %></td>
              <td><%= job.experience %></td>
              <td><%= job.salary %></td>
              <% if current_user.check_if_applied(job) %>
                <td ><%= link_to 'Cancel',applied_user_path(job.id),remote: true,class: "btn btn-danger",
                                         id:"apply", method: :delete,
                                         data: { confirm: 'Are you sure?' } %></td>
              <%else %>
                <td><%= link_to 'Apply', new_applied_users_path(job_id: job.id),remote: true,
                                         class: "btn btn-success", id:"apply", method: :post,
                                         data: { disable_with: 'Please wait....' }  %></td>
              <% end %>
            </tr>
           <% end %>
      </table>
      <hr/>

      <div id="paginate">
        <%= paginate @jobs %>
      </div>
      <br/><br/><br/><br/><br/>
      <br/><br/><br/><br/><br/>
      <br/><br/><br/><br/><br/>
      <br/>

<% end -%>
</div>

app/views/jobs/new.html.erb
<% provide(:title, 'Create Job') %>
<% provide(:button_text, "Create Jobs") %>


<div class="container">
  <div class="row">

    <div class="col-md-4">
        <%= render 'error_message' %>
    </div>

    <div class="col-md-4">
        <h3>Create Job</h3>
        <br/>
        <%= render 'common_form' %>
    </div>

    <div class="col-md-4">
    </div>

  </div>
</div>

app/views/jobs/view.html.erb
 <div class="container">
  <% provide(:title, 'Applied user') %>
  <h3>My Jobs</h3>
  <hr/>
    <table id="customers" >
    <tr>
      <th>Job Title</th>
      <th>Experience</th>
      <th>Salary</th>
      <th>Applied Users</th>
    </tr>

    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.post %></td>
        <td><%= job.experience %></td>
        <td><%= job.salary %></td>
        <td><%= link_to 'Applied User', applied_user_path(job) %></td>
      </tr>
    <% end %>
</table>
  <hr/>
      <%= paginate @jobs %>
<br/><br/><br/><br/>
<br/><br/><br/><br/>
<br/><br/><br/><br/>
<br/><br/><br/><br/>
<br/>
</div>