config/routes.rb
Rails.application.routes.draw do


#devise
  devise_for :users, controllers: { registrations: 'users/registrations' }

#root page
  root 'static_pages#home'

#jobs
  resources :jobs
  get  '/new',  to: 'jobs#new'
  get  '/view', to: 'jobs#view'

# applied user
  resources :applied_users, only: [:destroy, :show] do
  	post ':job_id' => "applied_users#create", on: :collection, as: :new
  end
end

app/views/layouts/_footer.html.erb
  <!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
          <span><%= link_to "About Us",  '#' %></span> |
          <span><%= link_to "Help", '#' %></span> |
          <span><%= link_to "News", '#' %></span>
      </nav>
    </div>

    <!-- Default to the left -->
      <strong>
        We are here to help those who seek for help!
      </strong>
      <small>Copyright &copy; 2018 <a href="#">Company</a>.</small>
</footer>

app/views/layouts/_header.html.erb
  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <%= link_to 'Logo', root_path, class: 'logo' %>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown user user-menu">
            <%= link_to "HOME", root_path %>
          </li>

          <!-- Messages: style can be found in dropdown.less-->
          <!-- check the user is sign in or not -->
          <% if user_signed_in? %>
            <!-- check role of user -->
              <% if current_user.has_role? :admin %>

                <!-- Employer's Job Menu -->
                <li class="dropdown user user-menu">
                  <!-- Menu Toggle Button -->
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    JOBS
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Create Jobs', new_path %></li>
                    <li><%= link_to 'My Jobs', jobs_path %></li>
                    <li><%= link_to 'Applied User', view_path %></li>
                  </ul>
                <!-- Employer's Job Menu end -->
              <% else %>

                <!-- Employee's Job Menu -->
                <li class="dropdown user user-menu">
                  <!-- Menu Toggle Button -->
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    JOB
                  </a>
                  <ul class="dropdown-menu">
                  <li><%= link_to "All Jobs",jobs_path %></li>
                  <li><%= link_to "Applied jobs", '#' %></li>
                  </ul>
                <!-- Employee's Job Menu end -->
              <% end %>

              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.name.upcase %>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <%= link_to image_tag("demo_person.png", class:"img-circle", alt:"Random Name", width:"160",
                                          height:"160") %>
                  </li>

                  <!-- Menu Body -->
                    <p>
                    <center>
                      <%= current_user.name.capitalize! %> -
                      <% if current_user.has_role? :admin %>
                        Employer
                      <%else%>
                        Candidate
                      <% end -%>
                      <br/>
                      <small>Member since <%= time_tag(current_user.created_at.to_date) %></small>
                    </center>
                    </p>

                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <%= link_to 'Setting', edit_user_registration_path, class:"btn btn-default btn-flat" %>
                    </div>
                    <div class="pull-right">
                      <%= link_to 'Log out', destroy_user_session_path, class:"btn btn-default btn-flat",
                                             method: :delete %>
                    </div>
                  </li>
                </ul>
              </li>

          <% else %>
          <li class="dropdown user user-menu">
            <%= link_to "LOG IN", new_user_session_path %>
          <% end -%>
          </li>
        </ul>
      </div>
    </nav>
  </header>


<script type="text/javascript">

</script>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
    <% if user_signed_in? %>

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
        <br/>
        <br/>
          <%= link_to image_tag("demo_person.png", class:"img-circle", alt:"Random Name") %>
        </div>
        <div class="pull-center info">
          <center><%= current_user.name.upcase %></center>
        </div>
      </div>
      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">HEADER</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active">
          <%= link_to 'HOME', root_path %>
        </li>
        <!-- Check the role of the user     -->
        <% if current_user.has_role? :admin %>
          <li><%= link_to 'Create Jobs', new_path %> </li>
          <li><%= link_to 'My Jobs', jobs_path %></li>
          <li><%= link_to 'Applied User', view_path %></li>
        <% else %>
          <li><%= link_to "All Jobs",jobs_path %></li>
          <li><%= link_to "Applied jobs", '#' %></li>
        <% end -%>
      </ul>
      <!-- /.sidebar-menu -->
    <% else %>

      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">HEADER</li>
        <li class="active">
          <%= link_to 'HOME', root_path %>
        </li>
        <li><%= link_to 'ABOUT US', '#' %> </li>
        <li><%= link_to 'CONTACT US', '#' %></li>
        <li><%= link_to 'HELP', '#' %></li>
      </ul>
      <% end -%>
    </section>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim'%>
  </head>
<!--body start -->
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

  <!-- Header start -->
  <%= render 'layouts/header'%>
  <!-- Header End-->

  <!-- Sidebar Start -->
  <%= render 'layouts/sidebar'%>
  <!-- Sidebar Ends -->

  <!-- Content Start -->
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="container-fluid">
      <div id="error_explanation">
        <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>

      <%= yield %>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <!-- Content End -->

  <!-- Footer Start -->
  <%= render 'layouts/footer'%>
  <!-- Footer End -->

  </div>

</body>
</html>